# Generated by Django 2.2.12 on 2021-05-30 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('belt_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('users_books', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books_r', to='belt_app.User')),
            ],
        ),
        migrations.CreateModel(
            name='coment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(max_length=45)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('books_coments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coments_books', to='belt_app.book')),
                ('users_coments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coments_users', to='belt_app.User')),
            ],
        ),
        migrations.CreateModel(
            name='Auther',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('books', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books_authers', to='belt_app.book')),
            ],
        ),
    ]
