# Generated by Django 2.2.12 on 2021-05-31 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('belt_app', '0002_auther_book_coment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(max_length=45)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('liked_by', models.ManyToManyField(related_name='likes', to='belt_app.User')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='belt_app.User')),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='users_books',
        ),
        migrations.RemoveField(
            model_name='coment',
            name='books_coments',
        ),
        migrations.RemoveField(
            model_name='coment',
            name='users_coments',
        ),
        migrations.DeleteModel(
            name='Auther',
        ),
        migrations.DeleteModel(
            name='book',
        ),
        migrations.DeleteModel(
            name='coment',
        ),
    ]
